export const BLOCKCHAIN__SET_LOADING = '[BLOCKCHAIN] SET_LOADING';
export const BLOCKCHAIN__SET_CONTRACT = '[BLOCKCHAIN] SET_CONTRACT';
export const BLOCKCHAIN__SET_PROVIDER = '[BLOCKCHAIN] SET_PROVIDER';
export const BLOCKCHAIN__FETCH = '[BLOCKCHAIN] FETCH';
export const BLOCKCHAIN__SET_ACCOUNT = '[BLOCKCHAIN] SET_ACCOUNT';
export const BLOCKCHAIN__DISCONNECT = '[BLOCKCHAIN] DISCONNECT';
export const BLOCKCHAIN__SET_IS_CONNECTED = '[BLOCKCHAIN] SET_IS_CONNECTED';
export const BLOCKCHAIN__SET_TRANSACTION_LOADING = '[BLOCKCHAIN] SET_TRANSACTION_LOADING';
export const BLOCKCHAIN__SET_TRANSACTION_STATUS = '[BLOCKCHAIN] SET_TRANSACTION_STATUS';
export const BLOCKCHAIN__MINT = '[BLOCKCHAIN] MINT';

export const CONTRACT_INFO__SET_DATA = '[CONTRACT_INFO] SET_DATA';
export const CONTRACT_INFO__SET_BALANCE = '[CONTRACT_INFO] SET_BALANCE';
export const CONTRACT_INFO__SET_LOADING = '[CONTRACT_INFO] SET_LOADING';
export const CONTRACT_INFO__SET_OWNER = '[CONTRACT_INFO] SET_OWNER';
export const CONTRACT_INFO__FETCH = '[CONTRACT_INFO] FETCH';

export const DATABASE__SET_LOADING = '[DATABASE] LOADING_SET';
export const DATABASE__SET_ADDRESSES = '[DATABASE] ADDRESSES_SET';
export const DATABASE__FETCH = '[DATABASE] FETCH';
export const DATABASE__ADD_NEW_WHITELIST_ADDRESS = '[DATABASE] ADD_NEW_WHITELIST_ADDRESS';
